### ISSUE TITLE
Allow customizable css

### ISSUE THREAD

**Issue by prubin** [nilsga/maven-jetty-pluto-embedded#1]
In the documentation on http://bekkopensource.lighthouseapp.com/projects/22517/configuration ther is note of being able to add additional css to the page. 

```
          <!-- Use the org.apache.pluto.embedded.extraStyles property to include extra style sheets 
               you want to include in the portal page. Can be used to make the portal look like your
               production site
          <systemProperty>
            <name>org.apache.pluto.embedded.extraStyles</name>
            <value>myportalserver.css,otherstyles.css</value>
          </systemProperty>
          -->
```

Please implement this feature.

**Comment by nilsga** [comment]
I have added a fix for this now, but don't have a sample to test with right now. Could you check out the new code and give it a try?

**Comment by prubin** [comment]
ok the embedded portal executes now.  

I added the property and it inserted the css name in the output...  However it created an invalid path.  Note the /testclean instead of test/clean...  I has expected relative pathing not abosolute.  I almost got the style sheet from a remote server which would also have failed.  What do you think is within limits here?  how smart should it be? 

&lt;style type="text/css" title="currentStyle" media="screen"&gt;
        @import "/test/pluto.css";
        @import "/test/portlet-spec-1.0.css";
        @import "/test/portlet-spec-2.0.css"; 

```
        @import "/testcleansheet/styles/light_background/cleansheet.css";

</style>
```

**Comment by nilsga** [comment]
I'ts "designed" to accept absolute urls. It's more flexible that way. It doesn't support remote urls as it is now, but I guess I could check for http or https in the values in the system property.

**Comment by prubin** [comment]
with the path corrected, it works correctly now.

Thanks.

**Comment by nilsga** [comment]
Thanks for verifying.
