### ISSUE TITLE
Allow system properties to overide the name of the jsp files

### ISSUE THREAD

**Issue by prubin** [nilsga/maven-jetty-pluto-embedded#2]
The current jsp theme file assumes that portlest can be displaied in two columns.  Please add system properties to allow overiding the jsp file with alternate jsp files to acheive new formats.

**Comment by nilsga** [comment]
Can you give it a try? System property named "org.apache.pluto.embedded.customTheme"

**Comment by prubin** [comment]
There seems to be a problem with the tag library definitions on startup I get this error:

java.io.FileNotFoundException: C:\Users\rubinp\workspace\sp4ts-portlet-test\src\main\webapp\WEB-INF\tld\pluto.tld (The system cannot find the path specified)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:106)
    at java.io.FileInputStream.<init>(FileInputStream.java:66)

This was not happening before these changes.

jetty-pluto-web-web-default.xml:

   &lt;jsp-config&gt;
   &lt;taglib&gt;
   &lt;taglib-uri&gt;http://portals.apache.org/pluto&lt;/taglib-uri&gt;
   &lt;taglib-location&gt;/WEB-INF/tld/pluto.tld&lt;/taglib-location&gt;
   &lt;/taglib&gt;
   &lt;/jsp-config&gt;

**Comment by nilsga** [comment]
yes, of course... Try the latest fix.

**Comment by prubin** [comment]
Theme replacement is working fine.  

Thank You.

**Comment by nilsga** [comment]
Thanks for verifying.
