### ISSUE TITLE
Shared attribute between action and render phases

### ISSUE THREAD

**Issue by astik** [nilsga/maven-jetty-pluto-embedded#3]
Following http://www.theserverside.com/news/1363818/JSR-286-Portlets-Action-scoped-Request-Attributes ; I'd like to forward attribute from the action phase to the render phase so that I want to use the "javax.portlet.actionScopedRequestAttributes" property.
I created a simple portlet as defined in the above link. It doesn't work with the maven plugin. But if I package my portlet and deploy it to liferay, it works, so my code might be correct.
Does the plugin take care of this feature or am I missing something ?

**Comment by nilsga** [comment]
Hi!

The plugin only runs the portlet in the pluto portlet container, so this should be handled by pluto. But it can of course be that something needs to be customised for it to work properly with pluto/jetty. Some sample code would definitively help.

**Comment by astik** [comment]
As you said, it should be handle by pluto.
Unfortunately, it's not the case right now (and since 2009 apparently) : https://issues.apache.org/jira/browse/JS2-956
As it is not a "maven-jetty-pluto-embedded" issue, I'm closing this issue.
Thanx

**Comment by nilsga** [comment]
That's a JetSpeed issue. I think pluto should have implemented it. I'm reopening it. What does your portlet.xml look like?

**Comment by astik** [comment]
Just check the link I posted earlier. I didn't manage to make it work.
When we'll be able to make it work, I'll try again with my portlet =)

**Comment by nilsga** [comment]
I have checked with the pluto devs, and they confirm that this feature is not implemented, so I'm closing it again.
